
# Get all users
GET http://localhost:3000/users

# Get contacts by Id
GET http://localhost:3000/users/682507677da1364f35c3f9a8


# Create contact
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
"firstName": "Alexa",
"lastName": "Frost",
"email": "alexa.frost@email.com",
"favoriteColor": "Pink",
"birthday": "October 8, 1996"
}

PUT http://localhost:3000/users/682507d07da1364f35c3f9a9 HTTP/1.1
Content-Type: application/json
{
"firstName": "Matthew",
"lastName": "Morales",
"email": "matthew.morales@email.com",
"favoriteColor": "Blue",
"birthday": "May 9, 2003"
}